window.KARAOKE_DATA = {
  updatedAt: "2026-08-23T13:41:00-07:00",
  timezone: "America/Los_Angeles",
  city: "Coeur d'Alene",
  region: "North Idaho",
  recurring: [
    {
      id: "backwoods-monday",
      venue: "Backwoods Bar",
      day: 1,
      start: "21:00",
      end: "02:00",
      address: "1920 E Sherman Ave, Coeur d'Alene, ID 83814",
      area: "East Sherman",
      confidence: "verified",
      confidenceLabel: "Venue confirmed",
      sourceType: "Venue events page",
      sourceUrl: "https://backwoodsbar.co/events/",
      sourceChecked: "2026-08-23",
      phone: "208-771-7309",
      notes: "Recurring Monday karaoke listed by the venue. Dart league starts earlier at 7 PM.",
      tags: ["Monday", "9 PM", "Recurring"],
      indoorSmoking: "reported",
      age: "Check venue",
      food: "No kitchen; outside food reported allowed"
    },
    {
      id: "corner-tuesday",
      venue: "Corner Bar",
      day: 2,
      start: "21:00",
      end: "01:00",
      address: "1628 N 4th St, Coeur d'Alene, ID 83814",
      area: "North 4th",
      confidence: "reported",
      confidenceLabel: "Recently reported",
      sourceType: "Recent venue/review listing",
      sourceUrl: "https://www.postcard.inc/places/corner-bar-coeur-dalene-3ZtHmSeKsJE",
      sourceChecked: "2026-08-23",
      phone: "208-667-9084",
      notes: "Tuesday 9 PM–1 AM is recently reported, but not yet verified on a first-party calendar. Call before making a special trip.",
      tags: ["Tuesday", "9 PM", "Check first"],
      indoorSmoking: "yes",
      age: "Check venue",
      food: "No food details confirmed"
    },
    {
      id: "lakers-wednesday",
      venue: "Lakers Inn",
      day: 3,
      start: "21:00",
      end: "01:00",
      address: "407 N 2nd St, Coeur d'Alene, ID 83814",
      area: "Downtown",
      confidence: "verified",
      confidenceLabel: "Schedule confirmed",
      sourceType: "Karaoke host schedule + current corroboration",
      sourceUrl: "https://djwebrix.com/bin/wednesday/",
      sourceChecked: "2026-08-23",
      phone: "208-667-9806",
      notes: "Wednesday karaoke is consistently listed; DJ Webrix lists 9 PM–1 AM.",
      tags: ["Wednesday", "9 PM", "Recurring"],
      indoorSmoking: "yes",
      age: "Check venue",
      food: "Bar; food not confirmed"
    },
    {
      id: "sunset-wednesday",
      venue: "Sunset Bar",
      day: 3,
      start: "21:00",
      end: "01:00",
      address: "122 E Appleway Ave, Coeur d'Alene, ID 83814",
      area: "Appleway",
      confidence: "reported",
      confidenceLabel: "Schedule needs refresh",
      sourceType: "Current venue listing + older recurring report",
      sourceUrl: "https://www.restaurantji.com/id/coeur-dalene/sunset-bar-/",
      sourceChecked: "2026-08-23",
      phone: "208-667-9083",
      notes: "Karaoke remains a current venue feature; Wednesday/Thursday recurrence comes from an older report. Call to confirm tonight's host/time.",
      tags: ["Wednesday", "Reported", "Check first"],
      indoorSmoking: "yes",
      age: "Check venue",
      food: "Outside food reported allowed"
    },
    {
      id: "sunset-thursday",
      venue: "Sunset Bar",
      day: 4,
      start: "21:00",
      end: "01:00",
      address: "122 E Appleway Ave, Coeur d'Alene, ID 83814",
      area: "Appleway",
      confidence: "reported",
      confidenceLabel: "Schedule needs refresh",
      sourceType: "Current venue listing + older recurring report",
      sourceUrl: "https://www.restaurantji.com/id/coeur-dalene/sunset-bar-/",
      sourceChecked: "2026-08-23",
      phone: "208-667-9083",
      notes: "Karaoke remains a current venue feature; Wednesday/Thursday recurrence comes from an older report. Call to confirm tonight's host/time.",
      tags: ["Thursday", "Reported", "Check first"],
      indoorSmoking: "yes",
      age: "Check venue",
      food: "Outside food reported allowed"
    }
  ],
  watchlist: [
    {
      id: "black-lodge",
      venue: "Black Lodge",
      address: "206 N 3rd St, Coeur d'Alene, ID 83814",
      area: "Downtown",
      reason: "The venue explicitly programs karaoke, but does not publish a stable recurring karaoke night in the current calendar.",
      sourceUrl: "https://www.blacklodgerocks.com/items",
      sourceLabel: "Check current events",
      phone: "208-640-6298"
    },
    {
      id: "duelers",
      venue: "Duelers Piano Bar",
      address: "313 E Sherman Ave, Coeur d'Alene, ID 83814",
      area: "Downtown",
      reason: "Recent reports mention Saturday karaoke, but the recurrence is not strong enough yet to put in the confirmed weekly feed.",
      sourceUrl: "https://restaurantguru.com/Duelers-Piano-Bar-Coeur-dAlene",
      sourceLabel: "Check current schedule",
      phone: "208-292-4016"
    }
  ]
};
